name: test site31
favicon: null
layout_spectrum: 0.6255478831008077
typography_spectrum: 0.5005279837641865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5260433612857014
  lightness: 0.485535632353276
  saturation: 0.33479232667014003
  rhythmicContrast: 0.1778969164006412
purpose: []
